jingwangnet/urls.py
from django.contrib import admin
from django.urls import path
from services import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name="home"),
    path('services/new', views.new_cate, name="new"),
    path('services/<int:pk>/', views.view_cate, name="view"),
    path('services/<int:pk>/add', views.add_ser, name="add"),
]

services/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('new', new_cate, name="new"),
    path('<slug:slug>/', view_cate, name="view"),
    path('<slug:slug>/add', add_ser, name="add"),
]

app_name = 'services'

services/models.py
from django.db import models
from django.utils.text import slugify
from pypinyin import lazy_pinyin

# Create your models here.
class Category(models.Model):
    name = models.CharField(verbose_name="分类名", max_length=30, null=False)
    abbr = models.CharField(
        verbose_name="分类名缩写", 
        max_length=20, 
        null=False, 
        unique=True
    )
    resume = models.TextField(verbose_name="分类简介", default='')
    slug = models.SlugField(verbose_name="Slug", null=False, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(lazy_pinyin(self.abbr))
        super(Category, self).save(*args, **kwargs)

class Service(models.Model):
    name = models.CharField(verbose_name="服务名", max_length=20)
    category = models.ForeignKey(Category, verbose_name="服务分类", on_delete=models.CASCADE)
    abbr = models.CharField(
        verbose_name="服务名缩写", 
        max_length=20, 
        null=False, 
        unique=True
    )
    resume = models.TextField(verbose_name="服务简介")

services/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Service, Category

# Create your views here.
def home_page(request):
    context = {'services': Service.objects.all()}
    return render(request, 'home.html', context)

def new_cate(request):
    category = Category.objects.create(
        name = request.POST['new_category_name'],
        abbr = request.POST['new_category_abbr'],
        resume = request.POST['new_category_resume']
    )
    Service.objects.create(
        name=request.POST['new_service_name'],
        abbr = request.POST['new_service_abbr'],
        resume=request.POST['new_service_resume'],
        category=category
    )
    return redirect(f'/services/{category.slug}/')

def view_cate(request, slug):
    category = Category.objects.get(slug=slug)
    services = Service.objects.filter(category=category)
    context = {'category': category}
    return render(request, 'view_category.html', context)

def add_ser(request, slug):
    category = Category.objects.get(slug=slug)
    Service.objects.create(
        name=request.POST['new_service_name'],
        abbr = request.POST['new_service_abbr'],
        resume=request.POST['new_service_resume'],
        category=category
    )
    return redirect(f'/services/{category.slug}/')

services/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="device=device-width, initial-scale=1.0">
<title>{% block title %}静网{% endblock %}</title>
{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}"> {% endblock %}
</head>
<body>

  <header class="mashthead" rele="banner">
    <div class="logo">
      <a href="/">静网</a>  
    </div>
  </header>

  <main class="main-container" role="main">

    <header>
      {% block header %}{% endblock %}
    </header>

    {% block table %}
    {% endblock %}

    <aside>
      <form method="POST" action="{% block action_url %}{% endblock %}">
        <div class="fieldset">
          {% block input_category %}
          <fieldset>
            <legend>服务类型</legend>
            <input id="id_new_category_name" name="new_category_name" type="text" placeholder="服务类型名">
            <input id="id_new_category_abbr" name="new_category_abbr" type="text" placeholder="服务类型名缩写">
            <textarea id="id_new_category_resume" name="new_category_resume" placeholder="服务类型简介"></textarea>
          </fieldset>
          {% endblock %}
          <fieldset>
            <legend>服务</legend>
            <input id="id_new_service_name" name="new_service_name" type="text" placeholder="服务名">
            <input id="id_new_service_abbr" name="new_service_abbr" type="text" placeholder="服务名缩写">
            <textarea id="id_new_service_resume" name="new_service_resume" placeholder="服务简介"></textarea>
          </fieldset>
        </div>
        <input id="id_submit" type="submit" value="提交">
        {% csrf_token %}

      </form>
    </aside>

  </main>
  <footer class="main-footer" role="contentinfo">
    <p>&copy;静网 2022</p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

services/templates/home.html
{% extends 'base.html' %}
{% block title %}静网{% endblock %}
{% block action_url %}/services/new{% endblock %}
{% block header %}<h1>服务列表</h1>{% endblock %}
{% block table %}
    <article id="id_service_table">
    {% regroup services|dictsort:"category.name" by category as category_list %}
      {% for category, category_services in category_list %}
      <section>
        <header>
          <h1><a href="{% url 'services:view' category.slug %}">{{ category.name }}</a></h1>
          <p><abbr title="{{ category.name }}">{{ category.abbr }}</abbr>{{ category.resume }}</p>
        </header>
        <div class="wrapper">
          {% for service in category_services %}
          <article>
            <h1>{{ forloop.counter }}. {{ service.name }}</h1>
            <p><abbr title="{{ service.name }}">{{ service.abbr }}</abbr>{{ service.resume }}</p>
          </article>
          {% endfor %}
        </div>
      </section>
      {% empty %}
      <section>
        <header>
           <p>还有添加服务!</p>   
        </header>
      </section>
      {% endfor %}
    </article>
{% endblock %}

services/templates/view_category.html
{% extends "base.html" %}
{% block title %}静网{% endblock %}
{% block action_url %}/services/{{ category.slug }}/add{% endblock %}
{% block input_category %}{% endblock %}
{% block header %}
      <h1>{{ category.name }}</h1>
      <p><abbr title="{{ category.name }}">{{ category.abbr }}</abbr>{{ category.resume }}</p>
{% endblock %}
{% block table %}
    <article id="id_service_table" class="view_category">
      {% for service in category.service_set.all %}
      <article class="service">
        <h1>{{ forloop.counter }}. {{ service.name }}</h1>
        <p><abbr title="{{ service.name }}">{{ service.abbr }}</abbr>{{ service.resume }}</p>
      </article>
      {% empty %}
      <article>
        <p>还没有添加服务!</p>
      </article>
      {% endfor %}
    </article>
{% endblock %}